clear

iradinc  = '..';
eigendir = '/usr/include/eigen3';

# libdir = [prefix 'lib'];

mkoctfile(['-I' iradinc],...
          ['-I' eigendir],...
          '-v','screened_coulomb_theta.cpp')

mkoctfile(['-I' iradinc],...
          ['-I' eigendir],...
          '-v','screened_coulomb_ip.cpp')

mkoctfile(['-I' iradinc],...
          ['-I' eigendir],...
          '-v','screened_coulomb_xs.cpp')
