clear

prefix  = '/home/george/.local/';
eigendir = '/usr/include/eigen3';

# libdir = [prefix 'lib'];

mkoctfile(['-I' prefix 'include'],...
          ['-I' eigendir],...
          ['-L' prefix 'lib'],...
          '-liondedx',...
          ['-Wl,-rpath=' prefix 'lib'],...
          '-v','dedx.cpp')

mkoctfile(['-I' prefix 'include'],...
          ['-I' eigendir],...
          '-v','screened_coulomb_theta.cpp')

mkoctfile(['-I' prefix 'include'],...
          ['-I' eigendir],...
          '-v','screened_coulomb_ip.cpp')

mkoctfile(['-I' prefix 'include'],...
          ['-I' eigendir],...
          '-v','screened_coulomb_xs.cpp')


