#include "corteo.h"

#include <iostream>
#include <fstream>

#include "xs.h"

using std::cout;
using std::endl;
using std::ofstream;

int gencorteo4bit();
int gencorteo6bit();

int main(int argc, char* argv[])
{
    gencorteo4bit();
    //gencorteo6bit();
    return 0;
}

const char* preample = "/*\n"
                       " * file generated by gencorteo utility of Iradina++\n"
                       " * \n"
                       " * do not edit \n"
                       " */\n";


const char* func4bit =
    "const float* corteo4bitdata() { return corteo4bitdata_; } \n";

const char* func6bit =
    "const float* corteo6bitdata() { return corteo6bitdata_; } \n";

int gencorteo4bit()
{
    unsigned long nThetaErr = 0;
    XSquad< screeningZBL > xs_quad_zbl;
    ofstream ofs("corteo4bitdata.cpp");
    int k = 0;
    int klast = corteo4bit::rows * corteo4bit::cols - 1;

    cout << "Computing 4-bit corteo scattering table";
    // compute matrix for each reduced energy, reduced impact parameter pair

    ofs << preample << endl;

    ofs << "static const float corteo4bitdata_[] = {\n";

    for(corteo4bit::e_index ie; ie!=ie.end(); ie++) {

        if (ie % (corteo4bit::rows/10)==0) {
            cout << ".";
            cout.flush();
        }

        for(corteo4bit::s_index is; is!=is.end(); is++) {
            // calculations (summation) made using double to decrease numerical noise
            float sin2ThetaBy2 = xs_quad_zbl.sin2Thetaby2(*ie, *is);
            if(std::isnan(sin2ThetaBy2)) nThetaErr++;

            // store in matrix sin^2(theta_CM/2) as float
            // matrix[is+ie*s_index::dim] = (float)(sin2ThetaBy2);
            ofs << sin2ThetaBy2;
            if (k!=klast) ofs << ',';
            k++;
            if (k % 16 ==0) ofs << endl;
        }
    }

    ofs << "}; \n\n";

    ofs << func4bit << endl;

    cout << " done.\n";
    cout.flush();

    if(nThetaErr)
        cout << "ERROR: " << nThetaErr << " error(s) in theta evaluation.\n";

    return !nThetaErr;
}

int gencorteo6bit()
{
    unsigned long nThetaErr = 0;
    XSquad< screeningZBL > xs_quad_zbl;
    ofstream ofs("corteo6bitdata.cpp");
    int k = 0;
    int klast = corteo6bit::rows * corteo6bit::cols - 1;

    cout << "Computing 6-bit corteo scattering table";
    // compute matrix for each reduced energy, reduced impact parameter pair

    ofs << preample << endl;

    ofs << "static const float corteo6bitdata_[] = {\n";

    for(corteo6bit::e_index ie; ie!=ie.end(); ie++) {

        if (ie % (corteo6bit::rows/10)==0) {
            cout << ".";
            cout.flush();
        }

        for(corteo6bit::s_index is; is!=is.end(); is++) {
            // calculations (summation) made using double to decrease numerical noise
            float sin2ThetaBy2 = xs_quad_zbl.sin2Thetaby2(*ie, *is);
            if(std::isnan(sin2ThetaBy2)) nThetaErr++;

            // store in matrix sin^2(theta_CM/2) as float
            // matrix[is+ie*s_index::dim] = (float)(sin2ThetaBy2);
            ofs << sin2ThetaBy2;
            if (k!=klast) ofs << ',';
            k++;
            if (k % 16 ==0) ofs << endl;
        }
    }

    ofs << "}; \n\n";

    ofs << func6bit << endl;

    cout << " done.\n";
    cout.flush();

    if(nThetaErr)
        cout << "ERROR: " << nThetaErr << " error(s) in theta evaluation.\n";

    return !nThetaErr;
}
