// file generated by gendedx - do not edit

extern const float* dedxH[];
extern const float* dedxHe[];
extern const float* dedxLi[];
extern const float* dedxBe[];
extern const float* dedxB[];
extern const float* dedxC[];
extern const float* dedxN[];
extern const float* dedxO[];
extern const float* dedxF[];
extern const float* dedxNe[];
extern const float* dedxNa[];
extern const float* dedxMg[];
extern const float* dedxAl[];
extern const float* dedxSi[];
extern const float* dedxP[];
extern const float* dedxS[];
extern const float* dedxCl[];
extern const float* dedxAr[];
extern const float* dedxK[];
extern const float* dedxCa[];
extern const float* dedxSc[];
extern const float* dedxTi[];
extern const float* dedxV[];
extern const float* dedxCr[];
extern const float* dedxMn[];
extern const float* dedxFe[];
extern const float* dedxCo[];
extern const float* dedxNi[];
extern const float* dedxCu[];
extern const float* dedxZn[];
extern const float* dedxGa[];
extern const float* dedxGe[];
extern const float* dedxAs[];
extern const float* dedxSe[];
extern const float* dedxBr[];
extern const float* dedxKr[];
extern const float* dedxRb[];
extern const float* dedxSr[];
extern const float* dedxY[];
extern const float* dedxZr[];
extern const float* dedxNb[];
extern const float* dedxMo[];
extern const float* dedxTc[];
extern const float* dedxRu[];
extern const float* dedxRh[];
extern const float* dedxPd[];
extern const float* dedxAg[];
extern const float* dedxCd[];
extern const float* dedxIn[];
extern const float* dedxSn[];
extern const float* dedxSb[];
extern const float* dedxTe[];
extern const float* dedxI[];
extern const float* dedxXe[];
extern const float* dedxCs[];
extern const float* dedxBa[];
extern const float* dedxLa[];
extern const float* dedxCe[];
extern const float* dedxPr[];
extern const float* dedxNd[];
extern const float* dedxPm[];
extern const float* dedxSm[];
extern const float* dedxEu[];
extern const float* dedxGd[];
extern const float* dedxTb[];
extern const float* dedxDy[];
extern const float* dedxHo[];
extern const float* dedxEr[];
extern const float* dedxTm[];
extern const float* dedxYb[];
extern const float* dedxLu[];
extern const float* dedxHf[];
extern const float* dedxTa[];
extern const float* dedxW[];
extern const float* dedxRe[];
extern const float* dedxOs[];
extern const float* dedxIr[];
extern const float* dedxPt[];
extern const float* dedxAu[];
extern const float* dedxHg[];
extern const float* dedxTl[];
extern const float* dedxPb[];
extern const float* dedxBi[];
extern const float* dedxPo[];
extern const float* dedxAt[];
extern const float* dedxRn[];
extern const float* dedxFr[];
extern const float* dedxRa[];
extern const float* dedxAc[];
extern const float* dedxTh[];
extern const float* dedxPa[];
extern const float* dedxU[];

const float** dedx_data[] = { nullptr, 
    dedxH, dedxHe, dedxLi, dedxBe, dedxB, 
    dedxC, dedxN, dedxO, dedxF, dedxNe, 
    dedxNa, dedxMg, dedxAl, dedxSi, dedxP, 
    dedxS, dedxCl, dedxAr, dedxK, dedxCa, 
    dedxSc, dedxTi, dedxV, dedxCr, dedxMn, 
    dedxFe, dedxCo, dedxNi, dedxCu, dedxZn, 
    dedxGa, dedxGe, dedxAs, dedxSe, dedxBr, 
    dedxKr, dedxRb, dedxSr, dedxY, dedxZr, 
    dedxNb, dedxMo, dedxTc, dedxRu, dedxRh, 
    dedxPd, dedxAg, dedxCd, dedxIn, dedxSn, 
    dedxSb, dedxTe, dedxI, dedxXe, dedxCs, 
    dedxBa, dedxLa, dedxCe, dedxPr, dedxNd, 
    dedxPm, dedxSm, dedxEu, dedxGd, dedxTb, 
    dedxDy, dedxHo, dedxEr, dedxTm, dedxYb, 
    dedxLu, dedxHf, dedxTa, dedxW, dedxRe, 
    dedxOs, dedxIr, dedxPt, dedxAu, dedxHg, 
    dedxTl, dedxPb, dedxBi, dedxPo, dedxAt, 
    dedxRn, dedxFr, dedxRa, dedxAc, dedxTh, 
    dedxPa, dedxU};

